version: '2.1'
services:
  mongo: # MongoDB: https://hub.docker.com/_/mongo/
    image: mongo:3
    volumes:
      - ./.data/mongo:/data/db
  elasticsearch: # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docker.html
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.9
    volumes:
      - ./.data/es:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - xpack.security.enabled=false # Disable X-Pack security: https://www.elastic.co/guide/en/elasticsearch/reference/5.5/security-settings.html#general-security-settings
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  graylog: # Graylog: https://hub.docker.com/r/graylog/graylog/
    image: graylog/graylog:2.4
    volumes:
      - ./.data/graylog:/usr/share/graylog/data/journal
      - ./config/graylog:/usr/share/graylog/data/config
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper # CHANGE ME!
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918 # Password: admin
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
    links:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000 # Graylog web interface and REST API
      - 514:514 # Syslog TCP
      - 514:514/udp # Syslog UDP
      - 12201:12201 # GELF TCP
      - 12201:12201/udp # GELF UDP
